import React, { useEffect, useRef, useState } from 'react';
import { BookOpenText, Books, Camera, CaretLeft, ChatCircleDots, Lightbulb, NotePencil, Plus, Quotes, Sparkle, Trash, X } from '@phosphor-icons/react';
import { useOS } from '../context/OSContext';
import type { BookReadingStatus, BookRecord, CharacterProfile, ReaderDiscussionMessage, ReadingNote, ReadingNoteType } from '../types';
import { compressReaderCover } from '../utils/readerCover';
import { ReaderStore } from '../utils/readerStore';

type View = 'shelf' | 'detail' | 'notes';
const STATUS: Record<BookReadingStatus, string> = { READING: '正在读', FINISHED: '已读完', WISH: '想读' };
const STYLE: Record<BookReadingStatus, string> = { READING: 'bg-violet-600 text-white', FINISHED: 'bg-emerald-100 text-emerald-700', WISH: 'bg-amber-100 text-amber-700' };
const dateValue = (value?: number | null) => value ? new Date(value).toISOString().slice(0, 10) : '';
const fromDate = (value: string) => value ? new Date(`${value}T00:00:00`).getTime() : null;
const humanDate = (value: number) => new Date(value).toLocaleDateString('zh-CN', { month: 'short', day: 'numeric' });

const Cover: React.FC<{ blob?: Blob; title: string; className?: string }> = ({ blob, title, className = '' }) => {
  const [url, setUrl] = useState<string>();
  useEffect(() => { if (!blob) return setUrl(undefined); const next = URL.createObjectURL(blob); setUrl(next); return () => URL.revokeObjectURL(next); }, [blob]);
  return url ? <img src={url} alt={`${title}封面`} className={`object-cover ${className}`} /> : <div className={`flex items-center justify-center bg-gradient-to-br from-[#302852] via-violet-600 to-fuchsia-400 text-white ${className}`}><BookOpenText className="w-9 h-9" weight="duotone" /></div>;
};
const Card: React.FC<{ children: React.ReactNode; className?: string }> = ({ children, className = '' }) => <div className={`rounded-[1.45rem] border border-white/80 bg-white/70 shadow-[0_15px_35px_-24px_rgba(56,32,110,.55)] backdrop-blur-xl ${className}`}>{children}</div>;

const Avatar: React.FC<{ character: CharacterProfile; className?: string }> = ({ character, className = '' }) => character.avatar ? <img src={character.avatar} alt="" className={`object-cover ${className}`} /> : <span className={`flex items-center justify-center bg-violet-100 font-black text-violet-500 ${className}`}>{character.name.slice(0, 1)}</span>;

const Discussion: React.FC<{ book: BookRecord; scope: 'REVIEW' | 'NOTE'; note?: ReadingNote; apiConfig: any; addToast: (text: string, type: 'info' | 'success' | 'error') => void }> = ({ book, scope, note, apiConfig, addToast }) => {
  const { characters, activeCharacterId } = useOS();
  const [messages, setMessages] = useState<ReaderDiscussionMessage[]>([]); const [draft, setDraft] = useState(''); const [loading, setLoading] = useState(false); const [open, setOpen] = useState(false); const [characterId, setCharacterId] = useState(activeCharacterId || characters[0]?.id || ''); const [selectedIds, setSelectedIds] = useState<string[]>(activeCharacterId ? [activeCharacterId] : characters[0] ? [characters[0].id] : []); const [replyTargetId, setReplyTargetId] = useState<string>(); const scrollRef = useRef<HTMLDivElement>(null);
  const subject = scope === 'REVIEW' ? (book.review || '我还没有写下读后感。') : note?.content || '';
  const character = characters.find(item => item.id === characterId);
  useEffect(() => { if (open) ReaderStore.getDiscussionForScope(book.id, scope, note?.id).then(setMessages).catch(() => addToast('讨论记录读取失败', 'error')); }, [book.id, scope, note?.id, open]);
  useEffect(() => { scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' }); }, [messages, loading]);
  const askForReply = async (chosenCharacter?: CharacterProfile, question = '', replyToId?: string) => {
    const responder = chosenCharacter || character; if (loading) return;
    if (!responder) return addToast('先选一位角色做你的阅读笔友', 'error');
    if (!apiConfig?.apiKey || !apiConfig?.baseUrl || !apiConfig?.model) return addToast('请先在设置中配置 API', 'error');
    setLoading(true);
    try {
      const label = scope === 'REVIEW' ? '读后感' : note?.type === 'EXCERPT' ? '摘抄' : '阅读闪念'; const conversation = messages.slice(-6).map(item => `${item.role === 'user' ? '用户' : item.characterName || '笔友'}：${item.content}`).join('\n'); const target = replyToId ? messages.find(item => item.id === replyToId) : undefined;
      const response = await fetch(`${apiConfig.baseUrl.replace(/\/+$/, '')}/chat/completions`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiConfig.apiKey}` }, body: JSON.stringify({ model: apiConfig.model, temperature: 0.9, messages: [{ role: 'system', content: `你是「${responder.name}」，正在和用户做阅读笔友。请严格遵守你的角色设定：${(responder.description || responder.systemPrompt || '温柔、有主见的朋友').slice(0, 1200)}。只围绕用户给出的书、读后感或摘抄交流，不编造书中情节。像认真写一小段回信或留评论，而不是客服答复：真诚、有个人语气、能回应细节。中文，最多 180 字。` }, { role: 'user', content: `书名：《${book.title}》\n作者：${book.author || '未知'}\n用户写下的${label}：\n${subject}${conversation ? `\n\n之前的交流：\n${conversation}` : ''}${target ? `\n\n这一次请重点回复这条话：\n${target.role === 'user' ? '用户' : target.characterName || '笔友'}：${target.content}` : ''}${question ? `\n\n用户刚刚回复：${question}` : ''}` }] }) });
      if (!response.ok) throw new Error(`请求失败 (${response.status})`); const data = await response.json(); const answer = data?.choices?.[0]?.message?.content?.trim(); if (!answer) throw new Error('AI 没有返回内容');
      const reply = await ReaderStore.createDiscussionMessage({ bookId: book.id, scope, noteId: note?.id, replyToId, role: 'assistant', content: answer, characterId: responder.id, characterName: responder.name, characterAvatar: responder.avatar }); setMessages(items => [...items, reply]);
    } catch (error) { addToast(error instanceof Error ? error.message : 'AI 回复失败，请稍后再试', 'error'); } finally { setLoading(false); }
  };
  const sendToFriends = async () => {
    const friends = characters.filter(item => selectedIds.includes(item.id));
    if (!friends.length) return addToast('至少选一位笔友', 'error');
    const question = draft.trim();
    let targetId = replyTargetId;
    if (question) { const user = await ReaderStore.createDiscussionMessage({ bookId: book.id, scope, noteId: note?.id, replyToId: targetId, role: 'user', content: question }); setMessages(items => [...items, user]); setDraft(''); targetId = user.id; }
    for (const friend of friends) await askForReply(friend, question, targetId);
  };
  return <section className="mt-3">
    <button onClick={() => setOpen(value => !value)} className={`flex items-center gap-1.5 rounded-full border px-2.5 py-1.5 text-[10px] font-bold transition ${open ? 'border-violet-200 bg-violet-100 text-violet-700' : 'border-violet-100 bg-white/70 text-violet-500 hover:bg-violet-50'}`}>
      <ChatCircleDots className="h-3.5 w-3.5" weight="fill" />{messages.length ? `${messages.length} 封笔友回信` : '找笔友聊聊'}<span className="text-violet-300">›</span>
    </button>
    {open && <div className="mt-2 overflow-hidden rounded-2xl border border-violet-100 bg-[#fcfbff]">
      <div className="border-b border-violet-100 px-3 py-3"><p className="text-[10px] font-bold text-slate-400">选几位笔友一起读，也可以随时再邀请新角色</p><div className="mt-2 flex gap-2 overflow-x-auto pb-0.5">{characters.map(item => { const selected = selectedIds.includes(item.id); return <button key={item.id} disabled={loading} onClick={() => { setCharacterId(item.id); setSelectedIds(ids => selected ? ids.filter(id => id !== item.id) : [...ids, item.id]); }} className={`flex shrink-0 items-center gap-1.5 rounded-full border py-1 pl-1 pr-2 text-[10px] transition disabled:opacity-50 ${selected ? 'border-violet-300 bg-violet-100 text-violet-700' : 'border-slate-100 bg-white text-slate-500'}`}><Avatar character={item} className="h-5 w-5 rounded-full" />{item.name}{selected && <span className="text-violet-400">✓</span>}</button>})}{characters.length === 0 && <span className="text-[11px] text-slate-400">还没有可选择的角色</span>}</div></div>
      <div ref={scrollRef} className="max-h-64 space-y-3 overflow-y-auto px-3 py-3">{messages.length === 0 && <div className="rounded-xl border border-dashed border-violet-200 bg-white px-3 py-3 text-[11px] leading-5 text-slate-500">点任意一条话，选定接下来要回复的目标；再让一位或多位角色回信。</div>}{messages.map(message => message.role === 'user' ? <button key={message.id} onClick={() => setReplyTargetId(message.id)} className={`ml-8 block rounded-2xl rounded-br-md px-3 py-2 text-left text-[12px] leading-5 text-white ${replyTargetId === message.id ? 'bg-violet-700 ring-2 ring-violet-200' : 'bg-violet-600'}`}>{message.content}<span className="mt-1 block text-[9px] text-white/60">{replyTargetId === message.id ? '正在回复这条' : '点此回复'}</span></button> : <button key={message.id} onClick={() => setReplyTargetId(message.id)} className={`mr-4 flex gap-2 text-left ${replyTargetId === message.id ? 'rounded-xl bg-violet-50 p-1 ring-1 ring-violet-200' : ''}`}><div className="mt-0.5 h-6 w-6 shrink-0 overflow-hidden rounded-full bg-violet-100">{message.characterAvatar ? <img src={message.characterAvatar} alt="" className="h-full w-full object-cover" /> : <span className="flex h-full items-center justify-center text-[10px] font-bold text-violet-500">{message.characterName?.slice(0, 1) || '友'}</span>}</div><div><p className="mb-1 text-[10px] font-bold text-violet-500">{message.characterName || '阅读笔友'} 的回信 · {replyTargetId === message.id ? '正在回复' : '点此回复'}</p><p className="rounded-2xl rounded-tl-md bg-white px-3 py-2 text-[12px] leading-5 text-slate-600 shadow-sm">{message.content}</p></div></button>)}{loading && <div className="flex items-center gap-1.5 text-[11px] text-violet-400"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-violet-400" />笔友正在写回信…</div>}</div>
      <div className="border-t border-violet-100 bg-white/75 p-2">{replyTargetId && <div className="mb-1 flex items-center justify-between px-1 text-[9px] text-violet-500"><span>将回复已选中的那一条</span><button onClick={() => setReplyTargetId(undefined)} className="text-violet-300">取消</button></div>}<div className="flex items-end gap-2 rounded-xl border border-violet-100 bg-white p-1.5"><textarea value={draft} onChange={e => setDraft(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendToFriends(); } }} placeholder={replyTargetId ? '写下对这条回信的想法…' : '想继续讨论的话，在这里回复…'} rows={1} className="min-h-[34px] flex-1 resize-none bg-transparent px-2 py-1.5 text-xs leading-5 outline-none" /><button onClick={sendToFriends} disabled={loading || selectedIds.length === 0} className="rounded-lg bg-violet-500 px-2.5 py-2 text-[10px] font-bold text-white disabled:opacity-35">{draft.trim() ? `发给 ${selectedIds.length} 位` : `请 ${selectedIds.length || ''} 位回信`}</button></div></div>
    </div>}
  </section>;
};

const OmniReaderApp: React.FC = () => {
  const { closeApp, addToast, apiConfig, characters, activeCharacterId } = useOS(); const [books, setBooks] = useState<BookRecord[]>([]); const [notes, setNotes] = useState<ReadingNote[]>([]); const [view, setView] = useState<View>('shelf'); const [selectedId, setSelectedId] = useState<string>(); const [showBookForm, setShowBookForm] = useState(false); const [showNoteForm, setShowNoteForm] = useState(false); const [bookForm, setBookForm] = useState({ title: '', author: '', status: 'WISH' as BookReadingStatus, startDate: '', endDate: '', coverBlob: undefined as Blob | undefined }); const [noteForm, setNoteForm] = useState({ type: 'EXCERPT' as ReadingNoteType, content: '', pageNumber: '' }); const fileRef = useRef<HTMLInputElement>(null);
  const selected = books.find(book => book.id === selectedId); const selectedNotes = notes.filter(note => note.bookId === selectedId); const readingCount = books.filter(book => book.status === 'READING').length;
  const load = async () => { try { const [nextBooks, nextNotes] = await Promise.all([ReaderStore.getAllBooks(), ReaderStore.getAllReadingNotes()]); setBooks(nextBooks.sort((a, b) => b.updatedAt - a.updatedAt)); setNotes(nextNotes.sort((a, b) => b.timestamp - a.timestamp)); await ReaderStore.refreshReaderContextSnapshot(); } catch { addToast('阅读记录读取失败，请稍后重试', 'error'); } };
  useEffect(() => { load(); }, []);
  const saveBook = async (patch: Partial<BookRecord>) => { if (!selected) return; await ReaderStore.saveBook({ ...selected, ...patch }); await load(); };
  const addBook = async () => { if (!bookForm.title.trim()) return addToast('请填写书名', 'error'); await ReaderStore.createBook({ title: bookForm.title, author: bookForm.author, status: bookForm.status, startDate: fromDate(bookForm.startDate), endDate: fromDate(bookForm.endDate), coverBlob: bookForm.coverBlob, review: '' }); await load(); setShowBookForm(false); setBookForm({ title: '', author: '', status: 'WISH', startDate: '', endDate: '', coverBlob: undefined }); addToast('已放入你的数字书架', 'success'); };
  const chooseCover = async (file?: File) => { if (!file) return; try { const coverBlob = await compressReaderCover(file); setBookForm(value => ({ ...value, coverBlob })); } catch (error) { addToast(error instanceof Error ? error.message : '封面处理失败', 'error'); } };
  const addNote = async () => { if (!selected || !noteForm.content.trim()) return addToast('写下一点内容再保存吧', 'error'); await ReaderStore.createReadingNote({ bookId: selected.id, type: noteForm.type, content: noteForm.content, pageNumber: Number(noteForm.pageNumber) || undefined }); await load(); setNoteForm({ type: 'EXCERPT', content: '', pageNumber: '' }); setShowNoteForm(false); addToast('已收进灵感手账本', 'success'); };
  const removeBook = async () => { if (!selected || !window.confirm(`删除《${selected.title}》和全部笔记、讨论吗？`)) return; await ReaderStore.deleteBook(selected.id); await load(); setSelectedId(undefined); setView('shelf'); addToast('书籍、笔记和讨论已删除', 'info'); };
  const title = view === 'shelf' ? '阅读手账' : selected?.title || '阅读手账';
  return <div className="flex h-full flex-col overflow-hidden bg-[#f5f3ff] text-slate-700 animate-fade-in"><header className="shrink-0 border-b border-white bg-white/75 backdrop-blur-2xl" style={{ paddingTop: 'var(--safe-top)' }}><div className="flex items-center gap-2 px-4 py-3"><button onClick={() => view === 'shelf' ? closeApp() : setView(view === 'notes' ? 'detail' : 'shelf')} className="rounded-full p-2 hover:bg-violet-50"><CaretLeft className="h-6 w-6" /></button><div className="min-w-0"><h1 className="truncate font-black">{title}</h1><p className="text-[10px] text-slate-400">把读过的每一页留在这里</p></div>{view === 'shelf' && <button onClick={() => setShowBookForm(true)} className="ml-auto flex h-10 w-10 items-center justify-center rounded-full bg-violet-600 text-white shadow-lg shadow-violet-200"><Plus className="h-5 w-5" weight="bold" /></button>}</div></header><main className="flex-1 overflow-y-auto px-4 pt-4 pb-28" style={view === 'notes' ? { backgroundImage: 'radial-gradient(rgba(139,92,246,.16) .75px, transparent .75px)', backgroundSize: '5mm 5mm' } : undefined}>
    {view === 'shelf' && <><div className="rounded-[1.6rem] bg-gradient-to-br from-[#29234e] via-violet-700 to-fuchsia-500 p-5 text-white shadow-xl shadow-violet-200/70"><p className="text-[11px] text-white/70">你的阅读宇宙</p><div className="mt-2 flex items-end justify-between"><div><strong className="text-4xl tracking-tight">{books.length}</strong><span className="ml-1.5 text-sm text-white/75">本收藏</span></div><div className="text-right text-[11px] text-white/80"><p>{readingCount} 本正在读</p><p className="mt-1">{notes.length} 条灵感记录</p></div></div></div><div className="mb-3 mt-6"><p className="text-xs font-black text-violet-700">我的书架</p><p className="mt-1 text-[11px] text-slate-400">点击一本书，继续留下你的想法。</p></div>{books.length === 0 ? <Card className="p-10 text-center"><Books className="mx-auto h-10 w-10 text-violet-300" weight="duotone" /><p className="mt-3 text-sm font-bold">从第一本书开始</p><p className="mt-1 text-xs text-slate-400">把想读、正在读和读完的书放进来。</p></Card> : <div className="grid grid-cols-2 gap-x-4 gap-y-6">{books.map(book => <button key={book.id} onClick={() => { setSelectedId(book.id); setView('detail'); }} className="group text-left"><div className="relative aspect-[3/4] overflow-hidden rounded-[1.25rem] shadow-[0_12px_24px_-13px_rgba(40,25,80,.7)] transition group-active:scale-95"><Cover blob={book.coverBlob} title={book.title} className="h-full w-full" /><span className={`absolute bottom-2 left-2 rounded-full px-2 py-1 text-[9px] font-bold ${STYLE[book.status]}`}>{STATUS[book.status]}</span></div><div className="mt-2 px-0.5"><p className="truncate text-sm font-bold">{book.title}</p><p className="truncate text-[10px] text-slate-400">{book.author || '作者未知'} · {notes.filter(note => note.bookId === book.id).length} 条笔记</p></div></button>)}</div>}</>}
    {view === 'detail' && selected && <div className="space-y-4"><Card className="flex gap-4 p-4"><Cover blob={selected.coverBlob} title={selected.title} className="h-32 w-24 shrink-0 rounded-xl" /><div className="min-w-0 flex-1"><input value={selected.title} onChange={e => setBooks(items => items.map(book => book.id === selected.id ? { ...book, title: e.target.value } : book))} onBlur={() => saveBook({ title: books.find(book => book.id === selected.id)?.title || selected.title })} className="w-full bg-transparent text-lg font-black outline-none" /><input value={selected.author} placeholder="写下作者" onChange={e => setBooks(items => items.map(book => book.id === selected.id ? { ...book, author: e.target.value } : book))} onBlur={() => saveBook({ author: books.find(book => book.id === selected.id)?.author || '' })} className="mt-1 w-full bg-transparent text-xs text-slate-400 outline-none" /><select value={selected.status} onChange={e => saveBook({ status: e.target.value as BookReadingStatus })} className={`mt-3 rounded-full px-2.5 py-1 text-[11px] font-bold outline-none ${STYLE[selected.status]}`}>{(Object.keys(STATUS) as BookReadingStatus[]).map(status => <option key={status} value={status}>{STATUS[status]}</option>)}</select><p className="mt-3 text-[10px] text-slate-400">已收录 {selectedNotes.length} 条笔记</p></div></Card><Card className="p-4"><p className="text-xs font-black">阅读时间</p><div className="mt-2 grid grid-cols-2 gap-3"><Field label="开始"><input type="date" value={dateValue(selected.startDate)} onChange={e => saveBook({ startDate: fromDate(e.target.value) })} /></Field><Field label="读完"><input type="date" value={dateValue(selected.endDate)} onChange={e => saveBook({ endDate: fromDate(e.target.value) })} /></Field></div></Card><Card className="p-4"><div className="mb-2 flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-amber-100 text-amber-500"><Sparkle className="h-4 w-4" weight="fill" /></span><div><p className="text-xs font-black">读完以后</p><p className="text-[10px] text-slate-400">留住这本书最后给你的余韵</p></div></div><textarea value={selected.review} onChange={e => setBooks(items => items.map(book => book.id === selected.id ? { ...book, review: e.target.value } : book))} onBlur={e => saveBook({ review: e.target.value })} placeholder="这本书最后留给你的，是怎样的余韵？" rows={5} className="w-full resize-none rounded-xl bg-amber-50/65 p-3 text-sm leading-6 outline-none" /><Discussion book={selected} scope="REVIEW" apiConfig={apiConfig} addToast={addToast} /></Card><button onClick={() => setView('notes')} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-violet-600 py-3.5 text-sm font-black text-white shadow-lg shadow-violet-200"><NotePencil className="h-4 w-4" />查看摘抄与阅读闪念 <span className="rounded-full bg-white/20 px-1.5 text-[10px]">{selectedNotes.length}</span></button><button onClick={removeBook} className="w-full py-2 text-xs text-rose-400">删除这本书及全部内容</button></div>}
    {view === 'notes' && selected && <div className="space-y-4"><div className="flex items-center justify-between pt-1"><div><p className="text-xs font-black text-violet-700">灵感手账</p><p className="mt-1 text-[11px] text-slate-400">《{selected.title}》的摘抄与闪念</p></div><span className="rounded-full bg-violet-100 px-2.5 py-1 text-[10px] font-bold text-violet-600">{selectedNotes.length} 条</span></div>{selectedNotes.map(note => <div key={note.id} className="relative pl-5"><span className="absolute left-0 top-5 h-2.5 w-2.5 rounded-full border-2 border-white bg-violet-400" />{note.type === 'EXCERPT' ? <blockquote className="rounded-r-2xl rounded-bl-2xl border-l-4 border-amber-300 bg-amber-50/90 p-4 shadow-sm"><Quotes className="mb-1 h-4 w-4 text-amber-400" weight="fill" /><p className="text-sm leading-6">{note.content}</p><p className="mt-2 text-[10px] text-amber-600">{humanDate(note.timestamp)} {note.pageNumber ? `· P.${note.pageNumber}` : ''}</p><Discussion book={selected} scope="NOTE" note={note} apiConfig={apiConfig} addToast={addToast} /></blockquote> : <div className="rounded-2xl bg-violet-100/90 p-4 shadow-sm"><div className="flex gap-2 text-violet-500"><Lightbulb className="h-4 w-4" weight="fill" /><span className="text-[10px] font-bold">那一刻的想法</span></div><p className="mt-2 text-sm font-medium leading-6">{note.content}</p><p className="mt-2 text-[10px] text-violet-400">{humanDate(note.timestamp)}</p><Discussion book={selected} scope="NOTE" note={note} apiConfig={apiConfig} addToast={addToast} /></div>}<button onClick={async () => { await ReaderStore.deleteNote(note.id); await load(); }} aria-label="删除这条笔记" className="absolute -right-1 -top-2 p-1.5 text-slate-300 hover:text-rose-400"><Trash className="h-3.5 w-3.5" /></button></div>)}{selectedNotes.length === 0 && <Card className="p-9 text-center"><ChatCircleDots className="mx-auto h-8 w-8 text-violet-300" weight="duotone" /><p className="mt-3 text-xs text-slate-400">从一句摘抄或一个想法开始吧。</p></Card>}<button onClick={() => setShowNoteForm(true)} className="fixed bottom-28 right-5 flex h-14 w-14 items-center justify-center rounded-full bg-violet-600 text-white shadow-lg shadow-violet-200"><Plus className="h-6 w-6" weight="bold" /></button></div>}
  </main>{showBookForm && <Sheet title="放一本书进书架" onClose={() => setShowBookForm(false)}><Field label="书名"><input value={bookForm.title} onChange={e => setBookForm(v => ({ ...v, title: e.target.value }))} placeholder="例如：百年孤独" /></Field><Field label="作者"><input value={bookForm.author} onChange={e => setBookForm(v => ({ ...v, author: e.target.value }))} placeholder="可选" /></Field><Field label="阅读状态"><select value={bookForm.status} onChange={e => setBookForm(v => ({ ...v, status: e.target.value as BookReadingStatus }))}>{(Object.keys(STATUS) as BookReadingStatus[]).map(status => <option key={status} value={status}>{STATUS[status]}</option>)}</select></Field><Field label="封面（会自动压缩）"><input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={e => chooseCover(e.target.files?.[0])} /><button onClick={() => fileRef.current?.click()} className="flex w-full justify-center gap-2 rounded-xl border border-dashed border-violet-300 bg-violet-50/70 py-3 text-xs text-violet-600"><Camera className="h-4 w-4" />{bookForm.coverBlob ? '封面已选好' : '上传本地封面'}</button></Field><button onClick={addBook} className="w-full rounded-2xl bg-violet-600 py-3 text-sm font-black text-white">加入书架</button></Sheet>}{showNoteForm && <Sheet title="记下这一页" onClose={() => setShowNoteForm(false)}><div className="mb-4 flex gap-2">{(['EXCERPT', 'THOUGHT'] as ReadingNoteType[]).map(type => <button key={type} onClick={() => setNoteForm(v => ({ ...v, type }))} className={`flex-1 rounded-xl py-2 text-xs font-bold ${noteForm.type === type ? 'bg-violet-600 text-white' : 'bg-violet-50 text-slate-400'}`}>{type === 'EXCERPT' ? '原文摘抄' : '阅读闪念'}</button>)}</div><Field label="内容"><textarea value={noteForm.content} onChange={e => setNoteForm(v => ({ ...v, content: e.target.value }))} rows={6} placeholder={noteForm.type === 'EXCERPT' ? '摘下一段让你停留的文字…' : '这一刻，你想到了什么？'} /></Field><Field label="页码（可选）"><input type="number" value={noteForm.pageNumber} onChange={e => setNoteForm(v => ({ ...v, pageNumber: e.target.value }))} placeholder="例如 42" /></Field><button onClick={addNote} className="w-full rounded-2xl bg-violet-600 py-3 text-sm font-black text-white">收进手账</button></Sheet>}</div>;
};
const Field: React.FC<{ label: string; children: React.ReactNode }> = ({ label, children }) => <label className="mb-4 block text-[11px] font-bold text-slate-500">{label}<div className="mt-1.5 [&_input]:w-full [&_input]:rounded-xl [&_input]:bg-violet-50 [&_input]:p-3 [&_input]:text-sm [&_input]:outline-none [&_select]:w-full [&_select]:rounded-xl [&_select]:bg-violet-50 [&_select]:p-3 [&_textarea]:w-full [&_textarea]:rounded-xl [&_textarea]:bg-violet-50 [&_textarea]:p-3 [&_textarea]:text-sm [&_textarea]:outline-none">{children}</div></label>;
const Sheet: React.FC<{ title: string; onClose: () => void; children: React.ReactNode }> = ({ title, onClose, children }) => <div className="absolute inset-0 z-40 flex items-end bg-slate-900/25 backdrop-blur-sm" onClick={onClose}><section className="max-h-[88%] w-full overflow-y-auto rounded-t-[2rem] bg-white/95 p-5" style={{ paddingBottom: 'calc(var(--safe-bottom) + 16px)' }} onClick={e => e.stopPropagation()}><div className="mb-4 flex items-center justify-between"><h2 className="font-black">{title}</h2><button onClick={onClose} className="p-2"><X className="h-4 w-4" /></button></div>{children}</section></div>;
export default OmniReaderApp;
