import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Gift, Trophy, Sparkle, Plus, Check, Trash, UploadSimple } from '@phosphor-icons/react';
import { useOS } from '../context/OSContext';
import type { GalleryItem, LifeGoal, LifeGoalMilestone } from '../types';
import { GalleryStore } from '../utils/galleryStore';
import { DB } from '../utils/db';

const uid = (prefix: string) => `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
const emptyIcon = () => new Blob([`<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"><defs><linearGradient id="g"><stop stop-color="#818cf8"/><stop offset="1" stop-color="#f0abfc"/></linearGradient></defs><rect width="512" height="512" rx="100" fill="url(#g)"/><text x="256" y="290" text-anchor="middle" font-size="180">✦</text></svg>`], { type: 'image/svg+xml' });
const ageDeadline = (birthday: string, age: number) => { const [year, month, day] = birthday.split('-').map(Number); return new Date(year + age, month - 1, day).getTime(); };
const countdown = (target: number) => { let ms = Math.max(0, target - Date.now()); const days = Math.floor(ms / 86400000); ms -= days * 86400000; const hours = Math.floor(ms / 3600000); ms -= hours * 3600000; const minutes = Math.floor(ms / 60000); return `${days} 天 ${hours} 小时 ${minutes} 分`; };
const BlobImage: React.FC<{ blob: Blob; className: string }> = ({ blob, className }) => { const [url, setUrl] = useState(''); useEffect(() => { const next = URL.createObjectURL(blob); setUrl(next); return () => URL.revokeObjectURL(next); }, [blob]); return url ? <img src={url} className={className} alt="" /> : <div className={className} />; };

const StarlightGalleryApp: React.FC = () => {
  const { closeApp, userProfile, updateUserProfile, addToast } = useOS();
  const [tab, setTab] = useState<'goals' | 'gifts'>('goals');
  const [items, setItems] = useState<GalleryItem[]>([]);
  const [goals, setGoals] = useState<LifeGoal[]>([]);
  const [showCreate, setShowCreate] = useState(false);
  const [birthdayDraft, setBirthdayDraft] = useState(userProfile.birthday || '2000-01-03');
  const [title, setTitle] = useState('');
  const [goalType, setGoalType] = useState<'COUNTDOWN' | 'ONE_TIME'>('COUNTDOWN');
  const [targetAge, setTargetAge] = useState(30);
  const [targetDate, setTargetDate] = useState('');
  const [iconBlob, setIconBlob] = useState<Blob | null>(null);
  const [milestoneDraft, setMilestoneDraft] = useState<Record<string, string>>({});
  const [now, setNow] = useState(Date.now());

  const reload = async () => { const [nextItems, nextGoals] = await Promise.all([GalleryStore.list(), DB.getLifeGoals()]); setItems(nextItems); setGoals(nextGoals); };
  useEffect(() => { void reload(); }, []);
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 60000); return () => window.clearInterval(timer); }, []);
  const saveBirthday = () => { if (!/^\d{4}-\d{2}-\d{2}$/.test(birthdayDraft)) return addToast('请输入正确的生日', 'error'); updateUserProfile({ birthday: birthdayDraft }); addToast('生日已保存，目标年龄会自动换算', 'success'); };
  const createGoal = async () => {
    if (!title.trim()) return addToast('请填写目标名称', 'info');
    if (goalType === 'COUNTDOWN' && !userProfile.birthday) return addToast('请先保存生日', 'info');
    const deadline = goalType === 'COUNTDOWN' ? ageDeadline(userProfile.birthday || birthdayDraft, targetAge) : new Date(targetDate || Date.now()).getTime();
    const goal: LifeGoal = { id: uid('life_goal'), title: title.trim(), type: goalType, targetAge: goalType === 'COUNTDOWN' ? targetAge : undefined, targetDate: deadline, status: 'IN_PROGRESS', visionImageBlob: iconBlob || emptyIcon(), milestones: [] };
    await DB.saveLifeGoal(goal); setGoals(previous => [goal, ...previous]); setTitle(''); setIconBlob(null); setShowCreate(false); addToast('目标已加入荣誉勋章', 'success');
  };
  const toggleGoal = async (goal: LifeGoal) => { const next = { ...goal, status: goal.status === 'ACHIEVED' ? 'IN_PROGRESS' : 'ACHIEVED', completedAt: goal.status === 'ACHIEVED' ? undefined : Date.now() } as LifeGoal; await DB.saveLifeGoal(next); setGoals(previous => previous.map(item => item.id === goal.id ? next : item)); };
  const addMilestone = async (goal: LifeGoal) => { const text = milestoneDraft[goal.id]?.trim(); if (!text) return; const milestone: LifeGoalMilestone = { id: uid('milestone'), title: text, completed: false }; const next = { ...goal, milestones: [...goal.milestones, milestone] }; await DB.saveLifeGoal(next); setGoals(previous => previous.map(item => item.id === goal.id ? next : item)); setMilestoneDraft(previous => ({ ...previous, [goal.id]: '' })); };
  const toggleMilestone = async (goal: LifeGoal, id: string) => { const next = { ...goal, milestones: goal.milestones.map(item => item.id === id ? { ...item, completed: !item.completed } : item) }; await DB.saveLifeGoal(next); setGoals(previous => previous.map(item => item.id === goal.id ? next : item)); };
  const removeGoal = async (goal: LifeGoal) => { await DB.deleteLifeGoal(goal.id); setGoals(previous => previous.filter(item => item.id !== goal.id)); };
  const visibleGifts = useMemo(() => items.filter(item => item.type === 'GIFT'), [items]);

  return <div className="h-full overflow-y-auto bg-gradient-to-br from-indigo-100 via-purple-100 to-pink-100 px-5 pb-12 pt-[calc(var(--safe-top)+1rem)] text-slate-800"><div className="mb-5 flex items-center gap-3"><button onClick={closeApp} className="rounded-full bg-white/60 p-2"><ArrowLeft size={20} /></button><div><p className="text-[10px] uppercase tracking-[.3em] text-indigo-500">Starlight Gallery</p><h1 className="text-2xl font-black">星光纪念馆</h1></div><Sparkle className="ml-auto text-amber-400" size={26} weight="fill" /></div>
    <div className="mb-5 grid grid-cols-2 gap-1 rounded-3xl border border-white/70 bg-white/35 p-1 shadow-xl backdrop-blur-xl"><button onClick={() => setTab('goals')} className={`rounded-2xl py-2 text-sm font-bold ${tab === 'goals' ? 'bg-white/80 text-indigo-700 shadow' : 'text-slate-500'}`}><Trophy className="mr-1 inline" size={16} />荣誉勋章</button><button onClick={() => setTab('gifts')} className={`rounded-2xl py-2 text-sm font-bold ${tab === 'gifts' ? 'bg-white/80 text-pink-700 shadow' : 'text-slate-500'}`}><Gift className="mr-1 inline" size={16} />珍藏心意</button></div>
    {tab === 'goals' ? <><div className="mb-4 rounded-3xl border border-white/70 bg-white/45 p-4 shadow-lg backdrop-blur-xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold">我的生日</p><p className="mt-1 text-[11px] text-slate-500">{userProfile.birthday ? `用于计算年龄目标：${userProfile.birthday}` : '尚未设置，默认可改为你的真实生日'}</p></div><button onClick={saveBirthday} className="rounded-xl bg-indigo-600 px-3 py-2 text-[11px] font-bold text-white">保存生日</button></div><input type="date" value={birthdayDraft} onChange={event => setBirthdayDraft(event.target.value)} className="mt-3 w-full rounded-xl bg-white/80 px-3 py-2 text-sm" /></div><button onClick={() => setShowCreate(value => !value)} className="mb-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-indigo-600 py-3 text-sm font-bold text-white shadow-lg"><Plus size={18} />添加荣誉目标</button>{showCreate && <div className="mb-5 rounded-3xl border border-white/70 bg-white/60 p-4 shadow-lg backdrop-blur-xl"><input value={title} onChange={event => setTitle(event.target.value)} placeholder="目标名称，例如：练出腹肌" className="w-full rounded-xl bg-white px-3 py-2 text-sm" /><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={() => setGoalType('COUNTDOWN')} className={`rounded-xl py-2 text-xs font-bold ${goalType === 'COUNTDOWN' ? 'bg-indigo-100 text-indigo-700' : 'bg-white/70 text-slate-500'}`}>倒计时目标</button><button onClick={() => setGoalType('ONE_TIME')} className={`rounded-xl py-2 text-xs font-bold ${goalType === 'ONE_TIME' ? 'bg-indigo-100 text-indigo-700' : 'bg-white/70 text-slate-500'}`}>一次性完成</button></div>{goalType === 'COUNTDOWN' ? <label className="mt-3 flex items-center gap-2 text-xs">目标年龄<input type="number" min={1} max={120} value={targetAge} onChange={event => setTargetAge(Number(event.target.value) || 30)} className="w-20 rounded-xl bg-white px-2 py-2" />岁</label> : <label className="mt-3 block text-xs">完成日期<input type="date" value={targetDate} onChange={event => setTargetDate(event.target.value)} className="mt-1 w-full rounded-xl bg-white px-3 py-2" /></label>}<label className="mt-3 flex items-center gap-2 rounded-xl bg-white/70 px-3 py-2 text-xs"><UploadSimple size={16} />上传愿景图<input type="file" accept="image/*" onChange={event => { const file = event.target.files?.[0]; if (file) setIconBlob(file); }} className="min-w-0 flex-1 text-[10px]" /></label><button onClick={() => void createGoal()} className="mt-4 w-full rounded-xl bg-slate-900 py-2.5 text-xs font-bold text-white">保存目标</button></div>}
    <div className="grid gap-4">{goals.map(goal => { const overdue = goal.status !== 'ACHIEVED' && (goal.targetDate || 0) <= now; return <div key={goal.id} className={`rounded-3xl border border-white/70 bg-white/55 p-4 shadow-lg backdrop-blur-xl ${goal.status === 'IN_PROGRESS' ? 'grayscale' : ''}`}><div className="flex gap-3"><BlobImage blob={goal.visionImageBlob} className="h-20 w-20 rounded-2xl object-cover shadow-inner" /><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase tracking-widest text-indigo-500">{goal.type === 'COUNTDOWN' ? `🎯 ${goal.targetAge}岁前` : '一次性目标'}</p><h2 className="truncate text-lg font-black">{goal.title}</h2>{goal.status === 'ACHIEVED' ? <p className="mt-1 text-xs font-bold text-emerald-600">完成时间：{new Date(goal.completedAt || now).toLocaleString()}</p> : goal.type === 'COUNTDOWN' ? <p className="mt-1 text-xs font-bold text-indigo-700">⏳ 距离 {goal.targetAge} 岁还有：{overdue ? '已到期' : countdown(goal.targetDate || now)}</p> : <p className="mt-1 text-xs text-slate-500">等待手动完成</p>}</div></div><div className="mt-3 flex gap-2"><button onClick={() => void toggleGoal(goal)} className={`flex-1 rounded-xl py-2 text-xs font-bold ${goal.status === 'ACHIEVED' ? 'bg-slate-200 text-slate-600' : 'bg-emerald-600 text-white'}`}>{goal.status === 'ACHIEVED' ? '撤销完成' : '手动标记完成'}</button><button onClick={() => void removeGoal(goal)} className="rounded-xl bg-rose-50 px-3 text-rose-500"><Trash size={15} /></button></div><div className="mt-3 border-t border-white/70 pt-3"><p className="text-[10px] font-bold text-slate-500">子里程碑</p>{goal.milestones.map(milestone => <button key={milestone.id} onClick={() => void toggleMilestone(goal, milestone.id)} className={`mt-1 flex w-full items-center gap-2 text-left text-xs ${milestone.completed ? 'text-emerald-600 line-through' : 'text-slate-600'}`}><span className="grid h-4 w-4 place-items-center rounded border border-slate-300">{milestone.completed && <Check size={11} />}</span>{milestone.title}</button>)}<div className="mt-2 flex gap-2"><input value={milestoneDraft[goal.id] || ''} onChange={event => setMilestoneDraft(previous => ({ ...previous, [goal.id]: event.target.value }))} placeholder="添加子里程碑" className="min-w-0 flex-1 rounded-lg bg-white/75 px-2 py-1.5 text-xs" /><button onClick={() => void addMilestone(goal)} className="rounded-lg bg-indigo-100 px-2 text-indigo-700"><Plus size={14} /></button></div></div></div>})}</div></> : <div className="grid grid-cols-2 gap-4">{visibleGifts.map(item => <div key={item.id} className="rounded-3xl border border-white/70 bg-white/50 p-3 shadow-lg backdrop-blur-xl"><BlobImage blob={item.imageBlob} className="h-32 w-full rounded-2xl object-cover" /><h2 className="mt-2 truncate font-bold">{item.title}</h2><p className="mt-1 text-xs text-slate-500">{item.description}</p></div>)}</div>}
  </div>;
};
export default StarlightGalleryApp;
